export class SettingsConstants {
  static readonly PREF_NAME = 'deadliner_settings';

  static readonly KEY_PRIVACY_AGREE = 'is_privacy_agreed';

  static readonly KEY_BASIC_MODE = 'key_basic_mode';

  static readonly KEY_CLOUD_SYNC_ENABLE = 'cloud_sync_enable';
  static readonly KEY_WEBDAV_URL = 'webdav_url';
  static readonly KEY_WEBDAV_USERNAME = 'webdav_username';
  static readonly KEY_WEBDAV_PASSWORD = 'webdav_password';
  static readonly KEY_THEME_MODE = 'theme_mode'; // 0:跟随系统, 1:浅色, 2:深色

  static readonly KEY_VIBRATION_ENABLE = 'vibration';
  static readonly KEY_PROGRESS_DIRECTION = 'progress_direction';
  static readonly KEY_EXCITEMENT_TEXT = 'excitement_text';
  static readonly KEY_CONFETTI_AFTER_FINISHED = 'confetti_after_finished';
  static readonly KEY_FULL_SCREEN_ADD = 'full_screen_add'

  static readonly KEY_AI_PROVIDER = 'ai_provider';
  static readonly KEY_AI_MODEL = 'ai_model';
  static readonly KEY_AI_DEEPSEEK_API_KEY = 'ai_deepseek_api_key';
  static readonly KEY_AI_BASE_URL = 'ai_base_url';

  static readonly KEY_MAIN_LEFT_BUTTON = 'main_left_button';
  static readonly KEY_MAIN_RIGHT_BUTTON = 'main_right_button';
}