/* auto-generated by OHOS-RS */
/* eslint-disable */

export declare function extractTasksJson(text: string, preferredLang: string): string

export declare class DeadlinerCore {
  constructor(apiKey: string, baseUrl: string, modelId: string, storagePath: string, platform: string)
  processInput(text: string): Promise<void>
  submitToolResult(id: string, resultJson: string): Promise<void>
  getLatestTasksJson(): string
  getLatestHabitsJson(): string
  getLastMemorySyncJson(): string | null
  getLastFinishJson(): string | null
  drainEventsJson(): string
  pendingEventCount(): number
  getUserProfile(): string
  replaceMemorySnapshot(snapshotJson: string): Promise<void>
  exportMemorySnapshot(): string
}
export type DeadlinerCoreOhos = DeadlinerCore

