export class SettingsConstants {
  static readonly PREF_NAME = 'deadliner_settings';

  // Keys
  static readonly KEY_CLOUD_SYNC_ENABLE = 'cloud_sync_enable';
  static readonly KEY_WEBDAV_URL = 'webdav_url';
  static readonly KEY_WEBDAV_USERNAME = 'webdav_username';
  static readonly KEY_WEBDAV_PASSWORD = 'webdav_password';
  static readonly KEY_THEME_MODE = 'theme_mode'; // 0:跟随系统, 1:浅色, 2:深色

  static readonly KEY_VIBRATION_ENABLE = 'vibration';
}